### ISSUE TITLE
Explain button non-functional on MSSQL connections

### ISSUE THREAD

**Issue by VIDGuide** [kviklet/kviklet#90] opened 2024-04-26 00:25 UTC
Since MSSQL doesn't have the keyword "EXPLAIN", this one fails. 
I know there are execution plans on MSSQL, but they're a bit more complex to retrieve and render I think, so maybe if nothing else a quick patch to hide/grey that button on MSSQL data sources perhaps?

Very low impact issue, just QOL/UI

**Comment by VIDGuide** [comment] 2024-04-26 02:30
New PR up for this one, I added a check and change to SET SHOWPLAN_TEXT ON; for MSSQL. 
#92

**Comment by Askir** [comment] 2024-04-26 12:15
The change doesn't quite work yet because JDBC doesn't support the GO keyword to separate batches. i'm also not 100% certain yet that SET SHOWPLAN_TEXT ON is the exact equivalent for explain. Some sources seem to say it just returns the normal results + the execution plan? Which would be bad because the explain button by design works without successful reviews.

I'll try to get this working in another PR. If I don't manage to, removing the button is definitely still a good option :D

**Comment by Askir** [comment] 2024-04-26 13:33
Fixed in #97

**Closed by Askir** 2024-04-26 13:33 UTC

**Comment by VIDGuide** [comment] 2024-04-29 00:52
SET SHOWPLAN_TEXT ON
does block the execution of the query, so it's the same in that respect. Most people in the MSSQL world use SSMS to do plan inspection, and rarely see how the commands work under the hood. The UI allows for both "Execution Plan only" and "run and return an execution plan". In this case SHOWPLAN_TEXT is the one that ONLY returns the plan, and does NOT execute the query. But the output is, well, a bit unwieldy, and as you say, requires multiple statements to execute, which obviously doesn't work so well in this JDBC connection. 

Disabling the button makes sense for now :)

**Comment by VIDGuide** [comment] 2024-04-29 23:25
Oh that's awesome, great work! Yeah, unfortunately it's not the prettiest output by miles, it's really designed for SSMS to turn into pretty charts, but it's a good guidance on what is going to happen, I appreciate that! I'll pull a new image and check it out!
